### ISSUE TITLE
linting MEI files

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/sample-encodings#27]
A very small point, but I notice extraneous white space at the ends of lines in Bach_Ein_festeBurg.mei (yellow stuff):

<img width="639" alt="screen shot 2017-10-01 at 7 37 45 am" src="https://user-images.githubusercontent.com/3487289/31060681-51aa8bee-a6cc-11e7-82ab-045f968fdb16.png">

Here is a long line of spaces added when you removed the beams in measure 4 :-)

<img width="1193" alt="screen shot 2017-10-01 at 5 19 10 pm" src="https://user-images.githubusercontent.com/3487289/31060705-b46e24d4-a6cc-11e7-8586-66c89bcfa06a.png">

Also observe that the notes on the second staff are indented as if they were still inside of the beam element...

It would be good to have a consistent formatting of the MEI files so that important changes are easier to track over time in the repository.  For example, verovio code is supposed to use [clang-format](https://clang.llvm.org/docs/ClangFormat.html) to format the code automatically and avoid trivial formatting changes to be documented.

**Comment by pe-ro** [comment]
@craigsapp, I usually use oXygen's "pretty print" options to format MEI files.  The settings I use are:

- indent size: 2
- line width: 100

Performing this operation should remove trailing spaces from closing tags unless the containing element is allowed to have mixed content.  I admit that I haven't been consistent about applying this, however.  I'll format all the files tomorrow -- getting a little late tonight.

It's good to remember, however, that a user can override these settings in oXygen (and other XML editors, I presume) or ignore them completely because generally formatting isn't significant in XML.
