### ISSUE TITLE
Vivaldi `@dots` on `mRest`

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/sample-encodings#46]
The example `Music/Music_structure/mdivs_Vivaldi/Vivaldi_multiple_mdivs.mei` fails validation due to `@dots` on `mRest` elements, e.g.

```xml
<mRest xml:id="d471670e36" dur="2" dots="1"/>
```

As the corresponding section is in 3/4 meter the question is how to encode the `mRest` properly. My favourite is:

```xml
<mRest xml:id="d471670e36" />
```

or provide `@dur.ges` and delete `@dur` as its value would simply be wrong without `@dots`

```xml
<mRest xml:id="d471670e36" dur.ges="3b" />
```

although on could argue, why not allow `@dots`

**Comment by th-we** [comment]
Are we encoding visual or logical domain here? If visual, then I'd say it's not an `<mRest>`, it's a `<rest>`. If logical, then I'd agree we should probably delete `@dur`.

I think the fact that `@dur` on `<mRest>` is of type [att.duration.additive](http://music-encoding.org/guidelines/v3/attribute-classes/att.duration.additive.html) is a simple oversight. The only sensible type would be [att.duration.additive](http://music-encoding.org/guidelines/v3/attribute-classes/att.duration.additive.html) because that's the only way to encode an `<mRest>` in something like 5/4 meters. That's an easy change to make because all currently validating encodings would still validate.

**Comment by bwbohl** [comment]
@kepper or @KristinaRichts: can anyone of you answer the encoding guidelines behind this file from the MEI project concerning the above question by @th-we? As the answer might have impact on many other files in the sample-encodings…

**Comment by th-we** [comment]
The Vivaldi example is the only one with `@dots` on an `<mRest>`. Any other files should be fine I guess (independent of the question what type `@dur` should actually be of).

**Comment by pe-ro** [comment]
In v. 4 `mRest/@dur` can take multiple values that add up to the total duration of the rest; i.e., 
```
<mRest xml:id="d471670e20620" dur="2 4"/>
```
so that's how the dotted mRest elements have been encoded. Technically, this correct but redundant.  So, I agree that it would be better to drop `@dur`.
