### ISSUE TITLE
Bach_Ein_festeBurg.mei

### ISSUE THREAD

**Issue by axelberndt** [music-encoding/sample-encodings#9]
Measures n="4" and n="13" should have attribute metcon="false".

**Comment by pe-ro** [comment]
`@metcon` isn't required, so I'd say "Measures 4 and 13 **may** have it", rather than **should** have it.  But I'll add it nonetheless.

**Comment by craigsapp** [comment]
Since measures 1 and 5 have it, measures 4 and 13 should have it for consistency, of course.  It might be nice to have some field in an analytic section of the `meiHead` to indicate that `measures@metcon` fields are expected if the measure is under or overfilled.  Then if a measure does not have the duration of the time signature and does not have `@metcon`, this would be flagged as an error in the data. 

In an earlier version of MEI it was possible to say that two `<measures>`  link together to form a single metric cycle.  For example measures 4 and 5 are both partial measures, but they are partial due to splitting a complete measure into two pieces by a repeat barline.  Is there an explicit way to indicate the link between these?  `@next` and `@prev` seem reasonable, but why they are linked still would not be entirely clear.

The example encoding uses `@type=upbeat` for the 0th measure:

https://github.com/music-encoding/sample-encodings/blob/935382d656b0d79e5b6166663f650dfcb1787394/MEI%203.0/Music/Complete%20examples/Bach_Ein_festeBurg.mei#L376

```xml
                  <measure n="0" xml:id="d1e43" type="upbeat" metcon="false">
```

This is good for analytic purposes to indicate the the metric cycle ends at the end of the measure, so the beat positions within this measure can be identified correctly.  However, using `@type` is impromptu, and there is no semantic meaning defined in MEI for contents of `@type`.  It would also be useful to indicate that measure 5 has the same sort of function as measure 0, which in this case would mean adding `@type="upbeat"` to measure 5 as well.

Also, measure 5 should not be labeled measure 5, since measures "4" and "5" form a single cycle of the meter. (there are 12 measures in this chorale, not 13 as implied by the measure numbers in the data).  The measure numbers are coming from the MusicXML data that the file was converted from.  MusicXML would label measure 5 as measure 5 since `@n` in MusicXML is not strictly the measure number, but rather an index on the measure element so that the score data can be switched between `time-wise` and `part-wise` arrangements.  I.e., they are container indexes rather than measure numbers.
